### ISSUE TITLE
CRS problem in stats19 training vignette

### ISSUE THREAD

**Issue by agila5** [ropensci/stats19#135] opened 2019-12-19 09:37 UTC
Hi everyone. Yesterday I started working on #134 and I found two problems in the training Vignette. The first problem is here 

https://github.com/ropensci/stats19/blob/3a955a3bab4fe6e7c9ff2c4de79ff4bc42c4a2ab/vignettes/stats19-training.Rmd#L786

because I get a warning:

``` r
> zones = pct::get_pct_zones("isle-of-wight")[1:9]
trying URL 'https://github.com/npct/pct-outputs-regional-R/raw/master/commute/msoa/isle-of-wight/z.Rds'
Content type 'application/octet-stream' length 18894 bytes (18 KB)
==================================================
downloaded 18 KB

Loading required package: sp
Warning message:
In CPL_crs_from_proj4string(x) :
  GDAL Message 1: +init=epsg:XXXX syntax is deprecated. It might return a CRS with a non-EPSG compliant axis order.
``` 

and the second problem is here:

https://github.com/ropensci/stats19/blob/3a955a3bab4fe6e7c9ff2c4de79ff4bc42c4a2ab/vignettes/stats19-training.Rmd#L805

because I get an error, i.e.

``` r
> zones_containing_crashes = zones[crashes_sf, ]
Error in st_geos_binop("intersects", x, y, sparse = sparse, prepared = prepared) : 
  st_crs(x) == st_crs(y) is not TRUE
``` 

This is the output of `zones`: 

``` r
Simple feature collection with 18 features and 9 fields
geometry type:  MULTIPOLYGON
dimension:      XY
bbox:           xmin: -1.591613 ymin: 50.57491 xmax: -1.070027 ymax: 50.76684
epsg (SRID):    4326
proj4string:    +proj=longlat +ellps=WGS84 +towgs84=0,0,0,0,0,0,0 +no_defs
```

and this is the output of `crashes_sf`:

``` r
Simple feature collection with 3 features and 7 fields
geometry type:  POINT
dimension:      XY
bbox:           xmin: -1.3 ymin: 50.68 xmax: -1.1 ymax: 50.7
epsg (SRID):    4326
proj4string:    +proj=longlat +datum=WGS84 +no_defs
```
Can you reproduce the same problem? I run that code using @Robinlovelace Rstudio Pro server and with GEOS 3.8.0, GDAL 3.0.2 and PROJ 6.2.1. The weird thing is that I don't get any warning or error on my laptop that uses GEOS 3.6.1, GDAL 2.2.3, PROJ 4.9.3.  

The CRS looks the same but they are not, so I think this is related to https://github.com/r-spatial/sf/issues/1215. I know that this is not a problem of stats19 package but I decided to open this issue here because I'm not sure how to proceed with stats19 code. I don't understand if that's a problem related to PROJ6 discussion (so we just need to wait they sort it out) or not. That's just a vignette so the easy solution would be to simply set `EVAL=FALSE` and add a few sentences that explain the problem (which is still not clear to me so  it did not occur a few days ago).

**Comment by Robinlovelace** [comment] 2019-12-19 10:50
I think this may be related to or the same as https://github.com/ITSLeeds/pct/issues/56 - could you try re-installing `sp`, `rgdal` and `rgeos` to see if that solves it?

**Comment by Robinlovelace** [comment] 2019-12-19 10:55
Update: I can reproduce this issue

```
zones = pct::get_pct_zones("isle-of-wight")[1:9]
trying URL 'https://github.com/npct/pct-outputs-regional-R/raw/master/commute/msoa/isle-of-wight/z.Rds'
Content type 'application/octet-stream' length 18894 bytes (18 KB)
==================================================
downloaded 18 KB

Warning message:
In CPL_crs_from_proj4string(x) :
  GDAL Message 1: +init=epsg:XXXX syntax is deprecated. It might return a CRS with a non-EPSG compliant axis order.
> 
> 
> ## ---- echo=FALSE------------------------------------------------------------------------
> # class(zones)
> # names(zones)
> ## ---- echo=FALSE------------------------------------------------------------------------
> # class(zones)
> # names(zones)
> zones[1:2, c(1, 5, 6, 7, 8)]
Simple feature collection with 2 features and 5 fields
geometry type:  MULTIPOLYGON
dimension:      XY
bbox:           xmin: -1.345963 ymin: 50.72766 xmax: -1.282956 ymax: 50.76684
epsg (SRID):    4326
proj4string:    +proj=longlat +ellps=WGS84 +towgs84=0,0,0,0,0,0,0 +no_defs
      geo_code  all bicycle foot car_driver                       geometry
3491 E02003581 3506     202  838       1755 MULTIPOLYGON (((-1.300856 5...
3492 E02003582 3325     234  458       2110 MULTIPOLYGON (((-1.305353 5...
> ## ---- message=FALSE---------------------------------------------------------------------
> zones_containing_crashes = zones[crashes_sf, ]
Error in st_geos_binop("intersects", x, y, sparse = sparse, prepared = prepared) : 
  st_crs(x) == st_crs(y) is not TRUE
```

**Comment by agila5** [comment] 2019-12-19 11:12
This is the result on my laptop

``` r
# packages
library(sf)
#> Linking to GEOS 3.6.1, GDAL 2.2.3, PROJ 4.9.3
    
# create crashes sf
crashes_sf <- st_as_sf(
    data.frame(
        vehicle_type = c("car", "bus", "tank"),
        casualty_type = c("pedestrian", "cyclist", "cat"), 
        longitude = c(-1.3, -1.2, -1.1), 
        latitude = c(50.7, 50.7, 50.68)
    ), 
    coords = c("longitude", "latitude"), 
    crs = 4326
)
# download data
zones = pct::get_pct_zones("isle-of-wight")[1:9]
#> Loading required package: sp
    
# spatial filter
zones[crashes_sf, ]
#> although coordinates are longitude/latitude, st_intersects assumes that they are planar
#> Simple feature collection with 3 features and 9 fields
#> geometry type:  MULTIPOLYGON
#> dimension:      XY
#> bbox:           xmin: -1.347353 ymin: 50.66522 xmax: -1.070027 ymax: 50.74036
#> epsg (SRID):    4326
#> proj4string:    +proj=longlat +datum=WGS84 +no_defs
#>       geo_code          geo_name   lad11cd      lad_name  all bicycle foot
#> 3496 E02003586 Isle of Wight 006 E06000046 Isle of Wight 2929      79  477
#> 3499 E02003589 Isle of Wight 009 E06000046 Isle of Wight 3332     132 1099
#> 3500 E02003590 Isle of Wight 010 E06000046 Isle of Wight 2338      85  304
#>      car_driver car_passenger                       geometry
#> 3496       1894           169 MULTIPOLYGON (((-1.169622 5...
#> 3499       1599           171 MULTIPOLYGON (((-1.31398 50...
#> 3500       1599            97 MULTIPOLYGON (((-1.107033 5...
```

<sup>Created on 2019-12-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

<details>

<summary>Session info</summary>

``` r
devtools::session_info()
#> - Session info ---------------------------------------------------------------
#>  setting  value                       
#>  version  R version 3.6.1 (2019-07-05)
#>  os       Windows 10 x64              
#>  system   x86_64, mingw32             
#>  ui       RTerm                       
#>  language EN                          
#>  collate  English_United Kingdom.1252 
#>  ctype    English_United Kingdom.1252 
#>  tz       Europe/Berlin               
#>  date     2019-12-19                  
#> 
#> - Packages -------------------------------------------------------------------
#>  package     * version date       lib source                       
#>  assertthat    0.2.1   2019-03-21 [1] CRAN (R 3.6.0)               
#>  backports     1.1.5   2019-10-02 [1] CRAN (R 3.6.1)               
#>  callr         3.4.0   2019-12-09 [1] CRAN (R 3.6.1)               
#>  class         7.3-15  2019-01-01 [2] CRAN (R 3.6.1)               
#>  classInt      0.4-2   2019-10-17 [1] CRAN (R 3.6.1)               
#>  cli           2.0.0   2019-12-09 [1] CRAN (R 3.6.1)               
#>  crayon        1.3.4   2017-09-16 [1] CRAN (R 3.6.0)               
#>  DBI           1.1.0   2019-12-15 [1] CRAN (R 3.6.1)               
#>  desc          1.2.0   2018-05-01 [1] CRAN (R 3.6.0)               
#>  devtools      2.2.1   2019-09-24 [1] CRAN (R 3.6.1)               
#>  digest        0.6.23  2019-11-23 [1] CRAN (R 3.6.1)               
#>  e1071         1.7-3   2019-11-26 [1] CRAN (R 3.6.1)               
#>  ellipsis      0.3.0   2019-09-20 [1] CRAN (R 3.6.1)               
#>  evaluate      0.14    2019-05-28 [1] CRAN (R 3.6.0)               
#>  fansi         0.4.0   2018-10-05 [1] CRAN (R 3.6.0)               
#>  fs            1.3.1   2019-05-06 [1] CRAN (R 3.6.1)               
#>  glue          1.3.1   2019-03-12 [1] CRAN (R 3.6.0)               
#>  highr         0.8     2019-03-20 [1] CRAN (R 3.6.0)               
#>  htmltools     0.4.0   2019-10-04 [1] CRAN (R 3.6.1)               
#>  KernSmooth    2.23-15 2015-06-29 [2] CRAN (R 3.6.1)               
#>  knitr         1.26    2019-11-12 [1] CRAN (R 3.6.1)               
#>  lattice       0.20-38 2018-11-04 [2] CRAN (R 3.6.1)               
#>  magrittr      1.5     2014-11-22 [1] CRAN (R 3.6.0)               
#>  memoise       1.1.0   2017-04-21 [1] CRAN (R 3.6.0)               
#>  pct           0.2.7   2019-09-26 [1] CRAN (R 3.6.1)               
#>  pkgbuild      1.0.6   2019-10-09 [1] CRAN (R 3.6.1)               
#>  pkgload       1.0.2   2018-10-29 [1] CRAN (R 3.6.0)               
#>  prettyunits   1.0.2   2015-07-13 [1] CRAN (R 3.6.0)               
#>  processx      3.4.1   2019-07-18 [1] CRAN (R 3.6.0)               
#>  ps            1.3.0   2018-12-21 [1] CRAN (R 3.6.0)               
#>  R6            2.4.1   2019-11-12 [1] CRAN (R 3.6.1)               
#>  Rcpp          1.0.3   2019-11-08 [1] CRAN (R 3.6.1)               
#>  remotes       2.1.0   2019-06-24 [1] CRAN (R 3.6.1)               
#>  rgeos         0.5-2   2019-10-03 [1] CRAN (R 3.6.1)               
#>  rlang         0.4.2   2019-11-23 [1] CRAN (R 3.6.1)               
#>  rmarkdown     2.0     2019-12-12 [1] CRAN (R 3.6.1)               
#>  rprojroot     1.3-2   2018-01-03 [1] CRAN (R 3.6.0)               
#>  sessioninfo   1.1.1   2018-11-05 [1] CRAN (R 3.6.0)               
#>  sf          * 0.8-1   2019-12-10 [1] Github (r-spatial/sf@60208b7)
#>  sp          * 1.3-2   2019-11-07 [1] CRAN (R 3.6.1)               
#>  stringi       1.4.3   2019-03-12 [1] CRAN (R 3.6.0)               
#>  stringr       1.4.0   2019-02-10 [1] CRAN (R 3.6.0)               
#>  testthat      2.3.1   2019-12-01 [1] CRAN (R 3.6.1)               
#>  units         0.6-5   2019-10-08 [1] CRAN (R 3.6.1)               
#>  usethis       1.5.1   2019-07-04 [1] CRAN (R 3.6.1)               
#>  withr         2.1.2   2018-03-15 [1] CRAN (R 3.6.0)               
#>  xfun          0.11    2019-11-12 [1] CRAN (R 3.6.1)               
#>  yaml          2.2.0   2018-07-25 [1] CRAN (R 3.6.0)               
#> 
#> [1] C:/Users/Utente/Documents/R/win-library/3.6
#> [2] C:/Program Files/R/R-3.6.1/library
```

</details>

and this is the result on the Rstudio Pro Server 

``` r
# packages
library(sf)
#> Linking to GEOS 3.8.0, GDAL 3.0.2, PROJ 6.2.1
    
# create crashes sf
crashes_sf <- st_as_sf(
    data.frame(
        vehicle_type = c("car", "bus", "tank"),
        casualty_type = c("pedestrian", "cyclist", "cat"), 
        longitude = c(-1.3, -1.2, -1.1), 
        latitude = c(50.7, 50.7, 50.68)
    ), 
    coords = c("longitude", "latitude"), 
    crs = 4326
)
# download data
zones = pct::get_pct_zones("isle-of-wight")[1:9]
#> Loading required package: sp
#> Warning in CPL_crs_from_proj4string(x): GDAL Message 1: +init=epsg:XXXX syntax
#> is deprecated. It might return a CRS with a non-EPSG compliant axis order.
    
# spatial filter
zones[crashes_sf, ]
#> Error in st_geos_binop("intersects", x, y, sparse = sparse, prepared = prepared): st_crs(x) == st_crs(y) is not TRUE
```

<sup>Created on 2019-12-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

<details>

<summary>Session info</summary>

``` r
devtools::session_info()
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value                       
#>  version  R version 3.6.2 (2019-12-12)
#>  os       Ubuntu 18.04.3 LTS          
#>  system   x86_64, linux-gnu           
#>  ui       X11                         
#>  language en_GB:en                    
#>  collate  en_GB.UTF-8                 
#>  ctype    en_GB.UTF-8                 
#>  tz       Europe/London               
#>  date     2019-12-19                  
#> 
#> ─ Packages ───────────────────────────────────────────────────────────────────
#>  package     * version date       lib source             
#>  assertthat    0.2.1   2019-03-21 [2] CRAN (R 3.6.0)     
#>  backports     1.1.5   2019-10-02 [2] CRAN (R 3.6.1)     
#>  callr         3.4.0   2019-12-09 [1] CRAN (R 3.6.2)     
#>  class         7.3-15  2019-01-01 [2] standard (@7.3-15) 
#>  classInt      0.4-2   2019-10-17 [1] CRAN (R 3.6.1)     
#>  cli           2.0.0   2019-12-09 [2] CRAN (R 3.6.1)     
#>  crayon        1.3.4   2017-09-16 [2] standard (@1.3.4)  
#>  DBI           1.1.0   2019-12-15 [2] CRAN (R 3.6.2)     
#>  desc          1.2.0   2018-05-01 [2] standard (@1.2.0)  
#>  devtools      2.2.1   2019-09-24 [2] CRAN (R 3.6.1)     
#>  digest        0.6.23  2019-11-23 [3] CRAN (R 3.6.1)     
#>  e1071         1.7-3   2019-11-26 [2] CRAN (R 3.6.1)     
#>  ellipsis      0.3.0   2019-09-20 [3] CRAN (R 3.6.1)     
#>  evaluate      0.14    2019-05-28 [2] CRAN (R 3.6.0)     
#>  fansi         0.4.0   2018-10-05 [2] standard (@0.4.0)  
#>  fs            1.3.1   2019-05-06 [2] CRAN (R 3.6.0)     
#>  glue          1.3.1   2019-03-12 [2] CRAN (R 3.5.3)     
#>  highr         0.8     2019-03-20 [3] CRAN (R 3.5.3)     
#>  htmltools     0.4.0   2019-10-04 [3] CRAN (R 3.6.1)     
#>  KernSmooth    2.23-16 2019-10-15 [4] CRAN (R 3.6.1)     
#>  knitr         1.26    2019-11-12 [3] CRAN (R 3.6.1)     
#>  lattice       0.20-38 2018-11-04 [2] standard (@0.20-38)
#>  magrittr      1.5     2014-11-22 [2] CRAN (R 3.5.2)     
#>  memoise       1.1.0   2017-04-21 [3] CRAN (R 3.5.0)     
#>  pct           0.2.7   2019-09-26 [2] CRAN (R 3.6.1)     
#>  pkgbuild      1.0.6   2019-10-09 [2] CRAN (R 3.6.1)     
#>  pkgload       1.0.2   2018-10-29 [3] CRAN (R 3.5.1)     
#>  prettyunits   1.0.2   2015-07-13 [2] CRAN (R 3.5.3)     
#>  processx      3.4.1   2019-07-18 [2] CRAN (R 3.6.1)     
#>  ps            1.3.0   2018-12-21 [2] CRAN (R 3.5.3)     
#>  R6            2.4.1   2019-11-12 [1] CRAN (R 3.6.1)     
#>  Rcpp          1.0.3   2019-11-08 [1] CRAN (R 3.6.1)     
#>  remotes       2.1.0   2019-06-24 [2] CRAN (R 3.6.0)     
#>  rgeos         0.5-2   2019-10-03 [1] CRAN (R 3.6.1)     
#>  rlang         0.4.2   2019-11-23 [1] CRAN (R 3.6.2)     
#>  rmarkdown     2.0     2019-12-12 [3] CRAN (R 3.6.2)     
#>  rprojroot     1.3-2   2018-01-03 [2] CRAN (R 3.5.3)     
#>  sessioninfo   1.1.1   2018-11-05 [3] CRAN (R 3.5.1)     
#>  sf          * 0.8-0   2019-09-17 [1] CRAN (R 3.6.1)     
#>  sp          * 1.3-2   2019-11-07 [2] CRAN (R 3.6.1)     
#>  stringi       1.4.3   2019-03-12 [2] CRAN (R 3.5.3)     
#>  stringr       1.4.0   2019-02-10 [2] standard (@1.4.0)  
#>  testthat      2.3.1   2019-12-01 [1] CRAN (R 3.6.2)     
#>  units         0.6-5   2019-10-08 [1] CRAN (R 3.6.1)     
#>  usethis       1.5.1   2019-07-04 [3] CRAN (R 3.6.1)     
#>  withr         2.1.2   2018-03-15 [2] CRAN (R 3.5.3)     
#>  xfun          0.11    2019-11-12 [3] CRAN (R 3.6.1)     
#>  yaml          2.2.0   2018-07-25 [3] CRAN (R 3.5.1)     
#> 
#> [1] /home/andrea/R/x86_64-pc-linux-gnu-library/3.6
#> [2] /usr/local/lib/R/site-library
#> [3] /usr/lib/R/site-library
#> [4] /usr/lib/R/library
```

</details>

I have no experience with these problems but this may imply that there is a problem of pct-outputs-regional data with new PROJ stuff.

**Comment by Robinlovelace** [comment] 2019-12-19 11:14
It's an upstream `gdal` version issue I think. Note it's `GDAL 3.0.2` on the remote instance vs `GDAL 2.2.3`. Apologies for unsolicited question @rsbivand but do you have any ideas how best to resolve this? I just tried to install the latest version of `rgdal` and I get this (can post this in the r-sig-geo list if appropriate):

```
install.packages("rgdal")
Installing package into ‘/home/robin/R/x86_64-pc-linux-gnu-library/3.6’
(as ‘lib’ is unspecified)
trying URL 'https://cloud.r-project.org/src/contrib/rgdal_1.4-8.tar.gz'
Content type 'application/x-gzip' length 1698902 bytes (1.6 MB)
==================================================
downloaded 1.6 MB

* installing *source* package ‘rgdal’ ...
** package ‘rgdal’ successfully unpacked and MD5 sums checked
** using staged installation
configure: R_HOME: /usr/lib/R
configure: CC: gcc -std=gnu99
configure: CXX: g++ -std=gnu++11
configure: C++11 support available
configure: rgdal: 1.4-7
checking for /usr/bin/svnversion... no
configure: svn revision: 845
checking for gdal-config... /usr/bin/gdal-config
checking gdal-config usability... yes
configure: GDAL: 3.0.2
checking GDAL version >= 1.11.4... yes
checking GDAL version <= 2.5 or >= 3.0... yes
checking gdal: linking with --libs only... no
checking gdal: linking with --libs and --dep-libs... no
/usr/bin/ld: cannot find -lStanHeaders
collect2: error: ld returned 1 exit status
/usr/bin/ld: cannot find -lStanHeaders
collect2: error: ld returned 1 exit status
configure: Install failure: compilation and/or linkage problems.
configure: error: GDALAllRegister not found in libgdal.
ERROR: configuration failed for package ‘rgdal’
* removing ‘/home/robin/R/x86_64-pc-linux-gnu-library/3.6/rgdal’
* restoring previous ‘/home/robin/R/x86_64-pc-linux-gnu-library/3.6/rgdal’
Warning in install.packages :
  installation of package ‘rgdal’ had non-zero exit status

The downloaded source packages are in
	‘/tmp/RtmpKMG4Bw/downloaded_packages’
```

**Comment by Robinlovelace** [comment] 2019-12-19 11:23
Interestingly, I installed the latest version with

```
sudo apt install r-cran-rgdal
```

And get 

```
remotes::install_cran("rgdal")
Skipping install of 'rgdal' from a cran remote, the SHA1 (1.4-8) has not changed since last install.
  Use `force = TRUE` to force installation
```

But still getting that issue...

**Comment by rsbivand** [comment] 2019-12-19 11:23
Looks like an incomplete GDAL install on remote, the StanHeaders error also suggests that remote is in a bad way. Sorry not more constructive.

**Comment by Robinlovelace** [comment] 2019-12-19 11:24
Thanks Roger. Just ran

```
sudo apt install r-cran-rgdal
```

**Comment by Robinlovelace** [comment] 2019-12-19 11:25
Looks like it's working, install worked this time...

**Comment by Robinlovelace** [comment] 2019-12-19 11:28
But despite new `rgdal` install it's still failing with

```
zones_containing_crashes = zones[crashes_sf, ]
Error in st_geos_binop("intersects", x, y, sparse = sparse, prepared = prepared) : 
  st_crs(x) == st_crs(y) is not TRUE
```

**Comment by Robinlovelace** [comment] 2019-12-19 11:30
It's due to a subtle difference in the CRS:

```
st_crs(zones)
Coordinate Reference System:
  EPSG: 4326 
  proj4string: "+proj=longlat +ellps=WGS84 +towgs84=0,0,0,0,0,0,0 +no_defs"
> st_crs(crashes_sf)
Coordinate Reference System:
  EPSG: 4326 
  proj4string: "+proj=longlat +datum=WGS84 +no_defs"
```

**Comment by Robinlovelace** [comment] 2019-12-19 11:30
And can be fixed with:

```
st_crs(zones) = 4326
Warning message:
st_crs<- : replacing crs does not reproject data; use st_transform for that 
> zones_containing_crashes = zones[crashes_sf, ]
```

**Comment by Robinlovelace** [comment] 2019-12-19 11:32
Final question @rsbivand (aplogies Roger but want to get this right): would it make sense to coerce the CRS to 4326 without the `+towgs84=0,0,0,0,0,0,0 ` part when the `zone` object is created in the `pct` package? I guess so, will open an issue in the appropriate place if so.

**Comment by Robinlovelace** [comment] 2019-12-19 11:53
Follow-on @rsbivand, I think it should be addressed `rgdal` side - round trip sf -> sp -> sf conversion changes the CRS and this will cause problems for many people I suspect. Please try to reproduce:

``` r
p = sf::st_as_sf(data.frame(x = 1:5, y = 2:6), coords = c("x", "y"), crs = 4326)
sf::st_crs(p)
#> Coordinate Reference System:
#>   EPSG: 4326 
#>   proj4string: "+proj=longlat +datum=WGS84 +no_defs"
p_sp = as(p, "Spatial")
sp::CRS(p_sp)
#> Warning in is.na(projargs): is.na() applied to non-(list or vector) of type 'S4'
#> Error in sp::CRS(p_sp): no method for coercing this S4 class to a vector
p2 = sf::st_as_sf(p_sp)
sf::st_crs(p2)
#> Coordinate Reference System:
#>   EPSG: 4326 
#>   proj4string: "+proj=longlat +ellps=WGS84 +towgs84=0,0,0,0,0,0,0 +no_defs"
```

<sup>Created on 2019-12-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by rsbivand** [comment] 2019-12-19 14:18
With my current GDAL/PROJ versions:

```
library(sf)
## Linking to GEOS 3.8.0, GDAL 3.1.0dev-2acbe38cb4, PROJ 6.2.1
p = sf::st_as_sf(data.frame(x = 1:5, y = 2:6), coords = c("x", "y"), crs = 4326)
sf::st_crs(p)
## Coordinate Reference System:
##  EPSG: 4326 
##  proj4string: "+proj=longlat +datum=WGS84 +no_defs"
p_sp = as(p, "Spatial")
sp::proj4string(p_sp)
## [1] "+proj=longlat +datum=WGS84 +no_defs"
p2 = sf::st_as_sf(p_sp)
sf::st_crs(p2)
## Coordinate Reference System:
##  EPSG: 4326 
##  proj4string: "+proj=longlat +datum=WGS84 +no_defs"
```

**Comment by Robinlovelace** [comment] 2019-12-20 09:51
Thanks Roger, I guess it's a temporary issue with `GDAL 3.0.2`.

**Closed** 2019-12-20 13:43 UTC
