### ISSUE TITLE
Vehicle IMD scores not labelled

### ISSUE THREAD

**Issue by PublicHealthDataGeek** [ropensci/stats19#139] opened 2020-01-06 16:55 UTC
Hello

Just to raise the fact that the Vehicle IMD scores are not labelled.  This is similar to the closed issue #92.

Thanks for sorting 

Caroline

library(stats19)
#> Data provided under OGL v3.0. Cite the source and link to:
#> www.nationalarchives.gov.uk/doc/open-government-licence/version/3/
casualties = get_stats19(year = 2017, type = "cas", ask = FALSE)
#> Files identified: dftRoadSafetyData_Casualties_2017.zip
#>    http://data.dft.gov.uk.s3.amazonaws.com/road-accidents-safety-data/dftRoadSafetyData_Casualties_2017.zip
#> Attempt downloading from:
#> Data saved at /var/folders/1r/vlxqbrms055dqt5cpxkrn13m0000gn/T//RtmpvYq7ck/dftRoadSafetyData_Casualties_2017/Cas.csv
vehicles = get_stats19(year = 2017, type = "veh", ask = FALSE)
#> Files identified: dftRoadSafetyData_Vehicles_2017.zip
#>    http://data.dft.gov.uk.s3.amazonaws.com/road-accidents-safety-data/dftRoadSafetyData_Vehicles_2017.zip
#> Attempt downloading from:
#> Data saved at /var/folders/1r/vlxqbrms055dqt5cpxkrn13m0000gn/T//RtmpvYq7ck/dftRoadSafetyData_Vehicles_2017/Veh.csv

unique(casualties$casualty_imd_decile)
#>  [1] "More deprived 10-20%"         "Data missing or out of range"
#>  [3] "More deprived 40-50%"         "Less deprived 10-20%"        
#>  [5] "More deprived 20-30%"         "More deprived 30-40%"        
#>  [7] "Less deprived 40-50%"         "Most deprived 10%"           
#>  [9] "Least deprived 10%"           "Less deprived 30-40%"        
#> [11] "Less deprived 20-30%"
unique(vehicles$driver_imd_decile)
#>  [1] "Data missing or out of range" "Less deprived 10-20%"        
#>  [3] "More deprived 10-20%"         "More deprived 40-50%"        
#>  [5] "More deprived 30-40%"         "More deprived 20-30%"        
#>  [7] "Less deprived 40-50%"         "Most deprived 10%"           
#>  [9] "Less deprived 20-30%"         "Less deprived 30-40%"        
#> [11] "Least deprived 10%"
unique(vehicles$vehicle_imd_decile)
#>  [1] -1  9  2  5  4  3  6  1  8  7 10

**Comment by PublicHealthDataGeek** [comment] 2020-01-06 16:56
![image](https://user-images.githubusercontent.com/43342160/71833731-7e9a4d00-30a5-11ea-98d0-4589482e9cc8.png)

**Comment by Robinlovelace** [comment] 2020-01-06 17:25
Hi Caroline, thanks for raising this issue. I tried to reproduce it but cannot. Can you try running the reproducible code below (output created using the package `reprex` which nicely formats code):

``` r
devtools::install_cran("stats19")
#> Skipping install of 'stats19' from a cran remote, the SHA1 (1.1.0) has not changed since last install.
#>   Use `force = TRUE` to force installation
library(stats19)
#> Data provided under OGL v3.0. Cite the source and link to:
#> www.nationalarchives.gov.uk/doc/open-government-licence/version/3/
dl_stats19(year = 2017, type = "vehicles", ask = FALSE)
#> Files identified: dftRoadSafetyData_Vehicles_2017.zip
#>    http://data.dft.gov.uk.s3.amazonaws.com/road-accidents-safety-data/dftRoadSafetyData_Vehicles_2017.zip
#> Attempt downloading from:
#> Data saved at /tmp/RtmphyeLQa/dftRoadSafetyData_Vehicles_2017/Veh.csv
x = read_vehicles(year = 2017, format = FALSE)
vehicles = format_vehicles(x)
head(vehicles$driver_imd_decile)
#> [1] "Data missing or out of range" "Data missing or out of range"
#> [3] "Less deprived 10-20%"         "More deprived 10-20%"        
#> [5] "Data missing or out of range" "Data missing or out of range"
```

<sup>Created on 2020-01-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>


I think the issue is that your packages are out of date. It's worth reguarly updating R packages, as outlined here (sections 4 and 5): https://www.datacamp.com/community/tutorials/r-packages-guide

**Comment by PublicHealthDataGeek** [comment] 2020-01-06 17:45
Hi Robin

I think the issue is with the last bit of your code where it asks for the head of the driver_imd_decile rather than the vehicle_imd_decile. If I change it to vehicle_imd_decile (see below) then it reproduces the issue (have also run the devtools install too)



``` r
library(stats19)
#> Data provided under OGL v3.0. Cite the source and link to:
#> www.nationalarchives.gov.uk/doc/open-government-licence/version/3/
dl_stats19(year = 2017, type = "vehicles", ask = FALSE)
#> Files identified: dftRoadSafetyData_Vehicles_2017.zip
#>    http://data.dft.gov.uk.s3.amazonaws.com/road-accidents-safety-data/dftRoadSafetyData_Vehicles_2017.zip
#> Attempt downloading from:
#> Data saved at /var/folders/1r/vlxqbrms055dqt5cpxkrn13m0000gn/T//RtmpxQxAFU/dftRoadSafetyData_Vehicles_2017/Veh.csv
x = read_vehicles(year = 2017, format = FALSE)
vehicles = format_vehicles(x)
head(vehicles$vehicle_imd_decile)
#> [1] -1 -1  9  2 -1 -1
```

<sup>Created on 2020-01-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by Robinlovelace** [comment] 2020-01-07 07:40
Good point @PublicHealthDataGeek, I missed that. On reflection, I think this is an issue with the raw STATS19 data, not the package. It seems the raw data contains 2 identical columns: `vehicle_imd_decile` and `driver_imd_decile`. Their 'identicality' is shown below:

``` r
# test imd vs
library(stats19)
#> Data provided under OGL v3.0. Cite the source and link to:
#> www.nationalarchives.gov.uk/doc/open-government-licence/version/3/
dl_stats19(year = 2017, type = "vehicles", ask = FALSE)
#> Files identified: dftRoadSafetyData_Vehicles_2017.zip
#>    http://data.dft.gov.uk.s3.amazonaws.com/road-accidents-safety-data/dftRoadSafetyData_Vehicles_2017.zip
#> Attempt downloading from:
#> Data saved at /tmp/RtmpD3q3VN/dftRoadSafetyData_Vehicles_2017/Veh.csv
x = read_vehicles(year = 2017, format = FALSE)
vehicles = format_vehicles(x)
head(vehicles$vehicle_imd_decile)
#> [1] -1 -1  9  2 -1 -1
head(vehicles$driver_imd_decile)
#> [1] "Data missing or out of range" "Data missing or out of range"
#> [3] "Less deprived 10-20%"         "More deprived 10-20%"        
#> [5] "Data missing or out of range" "Data missing or out of range"
summary(x$Vehicle_IMD_Decile == x$Driver_IMD_Decile)
#>    Mode    TRUE 
#> logical  238926
```

<sup>Created on 2020-01-07 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by PublicHealthDataGeek** [comment] 2020-01-07 10:07
Hi Robin

Yes I have gone back and looked at the DfT datasets and as you say the vehicle xls contains both driver and vehicle IMD. I have looked at the guidance and can't see any clear provenance for either data that was used as the source data for the IMD decile.  Given that you have show that the values are the same (at least for 2017) this suggests they must be using one data entry to derive both the driver and vehicle IMD - I would suggest the driver's postcode rather than checking the vehicle registration postcode.  Clearly there must be some drivers who drive vehicles that are not registered to them so I would expect there to have been some mismatch between driver and vehicle IMD but of course you found that they were the same.  

I will email the DfT to ask the question and link them to this page.  Assuming they will confirm my theory, then perhaps it is more appropriate to leave the vehicle IMD unlabelled if there is ambiguity as to whether that truly gives the vehicle IMD?

**Comment by Robinlovelace** [comment] 2020-01-07 10:16
> Assuming they will confirm my theory, then perhaps it is more appropriate to leave the vehicle IMD unlabelled if there is ambiguity as to whether that truly gives the vehicle IMD?

Sounds like a good plan to me especially because it stops the clean data from the package containing 2 identical variables which would be confusing and because it means less work (do nothing being a safe default in this case). Please let us know what they come back with and, if you're happy with the current behaviour of the package, close this issue.

Tbh I missed the `vehicle_imd` column completely so glad you spotted it.

**Comment by PublicHealthDataGeek** [comment] 2020-01-10 17:19
Hi Robin

So DfT have confirmed that the driver IMD and vehicle IMD are the same and are based on the drivers' postcodes if recorded.  Therefore I would suggest that you leave vehicle IMD unlabelled.  Many thanks

**Closed** 2020-01-10 18:14 UTC
